$thisRepoFolderPath = [System.IO.Path]::GetFullPath("$(git rev-parse --show-toplevel)")
$mainBicepRelativeFilePath = [System.IO.Path]::Join('.prereqs', 'AA-provision-webapp', 'bicep-definitions', '000-main.bicep')
$mainBicepFilePath = [System.IO.Path]::Join($thisRepoFolderPath, $mainBicepRelativeFilePath)
$outputArmTemplateRelativeFilePath = [System.IO.Path]::Join('.prereqs', 'AA-provision-webapp', 'equivalent-autogenerated-arm-template', 'azureprovision.json')

# # Update this repo's JSON
$outputArmTemplateFilePath = [System.IO.Path]::Join($thisRepoFolderPath, $outputArmTemplateRelativeFilePath)
az bicep build `
    --file $mainBicepFilePath `
    --outfile $outputArmTemplateFilePath

# Update this repo's README (https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-azure-button)
$readmeFilePath = [System.IO.Path]::Join($thisRepoFolderPath, 'README.md')
$thisRepoUrl = (git remote get-url origin).TrimEnd('.git').replace('github.com','raw.githubusercontent.com')
$thisRepoDefaultBranch = (((git remote show origin) | Select-String -Pattern "HEAD branch: (.*)").Matches[0].Groups[1].value)
$outputArmTemplateFileRawUrl = @($thisRepoUrl, $thisRepoDefaultBranch, $outputArmTemplateRelativeFilePath.replace('\','/')) | Join-String -Separator "/"
$webCreatorUrl = "https://portal.azure.com/#create/Microsoft.Template/uri/$([System.Uri]::EscapeDataString($outputArmTemplateFileRawUrl))"
@"

## AA-provision-webapp

[![Deploy AA-provision-webapp to Azure](https://aka.ms/deploytoazurebutton)]($webCreatorUrl)

"@ | Out-File -FilePath $readmeFilePath